
# The title and slogan are for the entire site.
# The "slogan" appears directly below the title, in smaller italics.
# The "image" is a URL that is relative to your site root.
# The title and image are required.  If you do not want a slogan, change it to
# "null" (_without_ the quotes).
title: "Globus @ Stanford"
slogan: "Research data management simplified.  For you.  For free."
image: "assets/globus_square.png"

# This section has site owner information.  It is used in a few places:
# * Page metadata, used by search engines and social tools.
# * The "Connect With Us" block at the bottom of each page.
owner:
  # The owner name must be provided.
  name: "Stanford Research Computing Center"

  # Next up is social media handles.  If you don't have one, use the word
  # "null", but without the quotes.

  # If you have a Facebook page, put your account name here.
  # Example, if your Facebook URL is https://facebook.com/xyz, put "xyz".
  facebook: null

  # If you have a Google Plus page, put in the page ID number.
  gplus: null

  # If you have a Twitter handle, put it here, _without_ the leading at-sign.
  twitter: "StanfordCompute"

  # If you have an Instagram account, put it here.
  instagram: null

  # If you have a YouTube account, put your account name here.
  youtube: null

  # If you have a GitHub org, put the name here.
  github: "stanford-rc"

  # If you have a Slack (which your visitors can join), put the workspace name
  # here.  Example: If you are at xyz.slack.com, put "xyz".
  slack: null

# If you would like to use the Google Search Console (also known as Google
# Webmaster Tools) with your site, you can provide your
# 'google-site-verification' code here.  See the instructions below:
#
# NOTE: Do not enable this until after your site is live at your preferred
# domain!
#
# 1) Go to https://google.com/webmasters/tools, signing in with your
#    Stanford Google account.
# 2) Choose "Add A Property", and paste in your web site's URL.
# 3) When asked for verification, go to the "Alternate methods tab" and
#    choose "HTML tag".
# 4) Examine the <meta> tag that Google wants you to add.  The tag's name
#    should be "google-site-verification".  Take the tag's content, and put
#    it here.
#
#    For example, if your tag says...
#       <meta name="google-site-verification" content="12545asbcdgre" />
#    ... then you would put in "12345asbcdgre" (_including_ the quotes).
# 5) Push your changes to GitHub, and wait a few minutes.
# 6) Go back to your web browser, and click the "Verify" button.
#    If Google can't verify your site, wait a few minutes and try again.
google-site-verification: null

# The index.html page of the site defaults to being your site's "blog page".
# (Altough the example calls it "Announcements", it's kindof the same thing.)
# By default, the full list of posts are split into pages of three posts per
# page.  For each additional page, a complete copy of index.html will be
# created, but with a different list of posts.
#
# You can change the number to whatever you want.  If you want to disable
# pagination entirely (and so have all posts appear on the main page), comment
# out the line below.
paginate: 3

# These defaults apply when a matching page variable is not set.
# NOTE: You should set most of these in page-specific YAML.
defaults:
  -
    scope:
      path: ""
    values:
      title: "Page Title"
      description: null
      layout: null
      sitemap: true
      social:
        # The title to use when Twitter et al show a link to your site.
        # When set to null, Jekyll will generate the string
        # "PAGE_TITLE â€” SITE_TITLE".
        title: null

        # The image to show when someone expands a Twitter post with your page
        # linked.  This should be a path relative to your site root.  If not
        # set, your site's image will be used instead.
        image: null

# These are Jekyll plugins that we enable.
# NOTE: We can only use plugins that GitHub makes available.
# The list is here: https://pages.github.com/versions/
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# This is a list of files that should be excluded from the _site directory.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - jekyll-theme-stanford-lagunita.gemspec
  - vendor

# These are some Jekyll defaults, which should be left alone.
timezone: America/Los_Angeles
encoding: utf-8
safe: true
